# Machine Learning KNN assignments 

In [160]:
import numpy as np
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn.model_selection import train_test_split


In [161]:
data=pd.read_csv('adult.data.txt',header=None,
  names=['age','workclass','final_weight','education','education_num','marital_status','occupation','relationship',
        'race','sex','capital-gain','capital-loss','hours-per-week','native-country','Class'])
data.fillna(0,inplace=True)
data.head()

age          workclass  final_weight   education  education_num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country   Class  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [162]:
data.describe()

age  final_weight  education_num  capital-gain  capital-loss  \
count  40560.000000  4.056000e+04   40560.000000  40560.000000  40560.000000   
mean      38.596031  1.894779e+05      10.075148   1090.381509     87.031262   
std       13.670550  1.054833e+05       2.574222   7507.980783    402.197372   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.174960e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783110e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.372772e+05      12.000000      0.000000      0.000000   
max       90.000000  1.490400e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    40560.000000  
mean        40.430966  
std         12.364265  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [163]:
test_data=pd.read_csv('adult.test.txt',header=None,
  names=['age','workclass','final_weight','education','education_num','marital_status','occupation','relationship',
        'race','sex','capital-gain','capital-loss','hours-per-week','native-country','Class'])
test_data.fillna(0,inplace=True)

In [164]:
test_data.head()


age workclass  final_weight      education  education_num  \
0   31   Private         57151   Some-college             10   
1   35   Private        399455        HS-grad              9   
2   37   Private         52630   Some-college             10   
3   42   Private        124692      Bachelors             13   
4   21   Private        278254   Some-college             10   

           marital_status          occupation    relationship    race  \
0           Never-married        Craft-repair   Not-in-family   White   
1   Married-spouse-absent       Other-service       Unmarried   White   
2      Married-civ-spouse        Craft-repair         Husband   White   
3      Married-civ-spouse     Exec-managerial         Husband   White   
4           Never-married   Handlers-cleaners       Own-child   Black   

       sex  capital-gain  capital-loss  hours-per-week  native-country   Class  
0     Male             0             0              40   United-States   <=50K  
1   Female             0             0              52   United-States   <=50K  
2     Male             0             0              40   United-States   <=50K  
3     Male             0             0              45   United-States    >50K  
4     Male             0             0              40   United-States   <=50K

In [165]:
##function to encod the categorial value 
def handle_non_numerical_data(data):
    columns=data.columns.values
    for column in columns:
        text_digit_vals={}
        def convert_to_int(val):
            return text_digit_vals[val]
        
        
        if data[column].dtype !=np.int64 and data[column].dtype !=np.float64:
            column_contents=data[column].values
            unique_elements = set(column_contents)
            x = 0
            for unique in unique_elements:
                if unique not in text_digit_vals:
                    text_digit_vals[unique] = x
                    x+=1

            data[column] = list(map(convert_to_int, data[column]))

    return data


# Data after encoding it to the numerical

In [166]:
data = handle_non_numerical_data(data)
data.head()


age  workclass  final_weight  education  education_num  marital_status  \
0   39          5         77516          4             13               0   
1   50          4         83311          4             13               3   
2   38          0        215646          6              9               2   
3   53          0        234721          2              7               3   
4   28          0        338409          4             13               3   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0          12             2     0    0          2174             0   
1           8             0     0    0             0             0   
2           5             2     0    0             0             0   
3           5             0     2    0             0             0   
4          14             5     2    1             0             0   

   hours-per-week  native-country  Class  
0              40              19      1  
1              13              19      1  
2              40              19      1  
3              40              19      1  
4              40              38      1

In [167]:
test_data=handle_non_numerical_data(test_data)
test_data.head()

age  workclass  final_weight  education  education_num  marital_status  \
0   31          0         57151          7             10               0   
1   35          0        399455          6              9               1   
2   37          0         52630          7             10               3   
3   42          0        124692          3             13               3   
4   21          0        278254          7             10               0   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           8             2     0    0             0             0   
1           2             4     0    1             0             0   
2           8             0     0    0             0             0   
3           9             0     0    0             0             0   
4           6             1     2    0             0             0   

   hours-per-week  native-country  Class  
0              40              19      1  
1              52              19      1  
2              40              19      1  
3              45              19      0  
4              40              19      1

In [168]:
##data is already in seperated files test file and train file so not reqired to split.



In [169]:
##seperating the label and the feature
##Train data sets
x_train=np.array(data.drop(['Class'],1).astype(float))
y_train=np.array(data['Class'])
##Test data sets
x_test=np.array(test_data.drop(['Class'],1).astype(float))
y_test=np.array(test_data['Class'])


In [170]:
#scaling the features 
from sklearn.preprocessing import StandardScaler
scal=StandardScaler()

In [171]:
##scaling the train features
x_train=scal.fit_transform(x_train)
x_train[:5]

array([[ 0.02955071,  1.97830247, -1.06143171, -0.7593041 ,  1.13622236,
        -1.26891366,  1.12416679,  0.37692482, -0.38234624, -0.70416689,
         0.14433066, -0.2163921 , -0.03485624, -0.14669158],
       [ 0.83421002,  1.46746728, -1.0064934 , -0.7593041 ,  1.13622236,
         0.6583336 ,  0.22866177, -0.93546858, -0.38234624, -0.70416689,
        -0.14523145, -0.2163921 , -2.21859573, -0.14669158],
       [-0.04360014, -0.57587348,  0.24808136, -0.04316936, -0.41766458,
         0.01591785, -0.44296699,  0.37692482, -0.38234624, -0.70416689,
        -0.14523145, -0.2163921 , -0.03485624, -0.14669158],
       [ 1.05366256, -0.57587348,  0.42891797, -1.47543884, -1.19460805,
         0.6583336 , -0.44296699, -0.93546858,  2.27722561, -0.70416689,
        -0.14523145, -0.2163921 , -0.03485624, -0.14669158],
       [-0.77510861, -0.57587348,  1.41191074, -0.7593041 ,  1.13622236,
         0.6583336 ,  1.57191929,  2.34551493,  2.27722561,  1.4201179 ,
        -0.14523145, -0.21

In [172]:
##scaling the test features
x_test=scal.fit_transform(x_test)
x_test[:5]

array([[-0.5665637 , -0.57887835, -1.25649106,  0.33944851, -0.03620016,
        -1.2717981 ,  0.19627019,  0.39719471, -0.38125667, -0.704483  ,
        -0.14274192, -0.22070133, -0.03037007, -0.1347941 ],
       [-0.27883936, -0.57887835,  1.9670516 , -0.00318556, -0.42759665,
        -0.62674746, -1.17875566,  1.72203024, -0.38125667,  1.41948067,
        -0.14274192, -0.22070133,  0.92781997, -0.1347941 ],
       [-0.13497718, -0.57887835, -1.29906618,  0.33944851, -0.03620016,
         0.66335382,  0.19627019, -0.92764081, -0.38125667, -0.704483  ,
        -0.14274192, -0.22070133, -0.03037007, -0.1347941 ],
       [ 0.22467825, -0.57887835, -0.62044446, -1.03108776,  1.13798932,
         0.66335382,  0.42544117, -0.92764081, -0.38125667, -0.704483  ,
        -0.14274192, -0.22070133,  0.36887578, -0.1347941 ],
       [-1.28587458, -0.57887835,  0.82567845,  0.33944851, -0.03620016,
        -1.2717981 , -0.26207176, -0.26522305,  2.33493065, -0.704483  ,
        -0.14274192, -0.22

In [173]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(40560, 14) (40560,) (8282, 14) (8282,)


In [174]:
#impor the classifier 
clf=KNeighborsClassifier(n_neighbors=3)


In [175]:
clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [176]:
predication=clf.predict(x_test)
predication[:10]

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [179]:
clf.score(x_test,y_test)

0.81695242695001202